CREATE TABLE IF NOT EXISTS Users (
    ID TEXT PRIMARY KEY NOT NULL UNIQUE, --Twitch ID
    Points INTEGER NOT NULL DEFAULT 100,
    Username TEXT NOT NULL,
    RPGData BLOB
);

CREATE TABLE IF NOT EXISTS AFKStatus (
    ID TEXT PRIMARY KEY NOT NULL UNIQUE,
    AFK BOOLEAN NOT NULL DEFAULT 0,
    Reason TEXT NOT NULL DEFAULT '',
    Time DATETIME NOT NULL DEFAULT(DATETIME('now'))
);