CREATE TABLE IF NOT EXISTS Users (
	ID TEXT PRIMARY KEY NOT NULL UNIQUE, --Twitch ID
	Points INTEGER NOT NULL DEFAULT 100,
	Username TEXT NOT NULL
);

CREATE TABLE Players (
	UserID TEXT PRIMARY KEY NOT NULL UNIQUE,
	FOREIGN KEY(UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE State (
	PlayerID TEXT PRIMARY KEY NOT NULL UNIQUE,
	HP INTEGER NOT NULL,
	FOREIGN KEY(PlayerID) REFERENCES Players(UserID) ON DELETE CASCADE
);

CREATE TABLE Stats (
	PlayerID TEXT PRIMARY KEY NOT NULL UNIQUE,
	Vitality INTEGER NOT NULL,
	Strength INTEGER NOT NULL,
	Dexterity INTEGER NOT NULL,
	FOREIGN KEY(PlayerID) REFERENCES Players(UserID) ON DELETE CASCADE
);

CREATE TABLE Weapon (
	ItemID INTEGER PRIMARY KEY NOT NULL UNIQUE,
	BaseDamage INTEGER NOT NULL,
	StrengthScaling INTEGER NOT NULL,
	DexterityScaling INTEGER NOT NULL,
	FOREIGN KEY(ItemID) REFERENCES Item(ID) ON DELETE CASCADE
);

CREATE TABLE Item (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	Name TEXT NOT NULL UNIQUE
);

CREATE TABLE InventoryItem (
	PlayerID INTEGER,
	ItemID INTEGER,
	Amount INTEGER NOT NULL,
	FOREIGN KEY(PlayerID) REFERENCES Players(UserID) ON DELETE CASCADE,
	FOREIGN KEY(ItemID) REFERENCES Item(ID) ON DELETE NO ACTION
);